AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template to create an IAM role assuming an existing AWS managed policy ARN'

Parameters:
  RoleName:
    Type: String
    Description: 'ReadOnlyRoleforaccessaccount'
  ManagedPolicyArn1:
    Type: String
    Description: 'arn:aws:iam::aws:policy/ReadOnlyAccess'
  ManagedPolicyArn2:
    Type: String
    Description: 'arn:aws:iam::aws:policy/AWSBillingReadOnlyAccess'
  ManagedPolicyArn3:
    Type: String
    Description: 'arn:aws:iam::aws:policy/CostOptimizationHubReadOnlyAccess'   
  DestinationAccountID:
    Type: String
    Description: 'xxxxxxxxxxxxxx' # source account
    MinLength: 12
    MaxLength: 12  

Resources:
  IAMRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Ref RoleName
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: 
              AWS: !Sub 'arn:aws:iam::${DestinationAccountID}:root'
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - !Ref ManagedPolicyArn1
        - !Ref ManagedPolicyArn2
        - !Ref ManagedPolicyArn3


Outputs:
  IAMRoleARN:
    Description: 'ARN of the IAM role'
    Value: !GetAtt IAMRole.Arn
